---
- name: Check if data exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/data"
  register: manager_setup_data_dir

- name: Extract data directory from archive only if not exists
  become: true
  ansible.builtin.unarchive:
    src: "{{ manager_setup_data_backup_file }}"
    dest: "{{ ansible_env.HOME }}"
    remote_src: true
    extra_opts:
      - --strip-components=1
      - ./data
  when: not manager_setup_data_dir.stat.exists
