$ANSIBLE_VAULT;1.1;AES256
65623338633166303833363236366365383635376264633632333835323164396436633436336639
3630373034353631653766646339336139396639353537320a303833316162323166643530343537
30393332306430323737653739386366383566323131636162633639316434633238383464633134
3763373231333961650a373738636339653535346437313865333964363465616135643761326232
35313766663532663065393939613234396366353933346638366532393239356635
