---
router_install_node_exporter_version: "1.10.2"
router_install_node_exporter_name: "node_exporter-{{ router_install_node_exporter_version }}.linux-armv7"
router_install_node_exporter_archive_filename: "{{ router_install_node_exporter_name }}.tar.gz"
router_install_node_exporter_url:
  https://github.com/prometheus/node_exporter/releases/download/v{{
  router_install_node_exporter_version }}/{{ router_install_node_exporter_archive_filename }}
router_install_node_exporter_install_dir: "{{ router_app_dir }}/node_exporter"
router_install_node_exporter_options: --no-collector.netdev --collector.filesystem.mount-points-exclude="^/data$|^/jffs$|^/tmp/mnt(/defaults)?$"
